apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-main-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-main
  template:
    metadata:
      labels:
        app: client-main
    spec:
      containers:
        - name: client-main
          image: fish29/client-main-react
---
apiVersion: v1
kind: Service
metadata:
  name: client-main-srv
spec:
  selector:
    app: client-main
  ports:
    - name: client-main
      protocol: TCP
      port: 3000
      targetPort: 3000
